# Site settings
title: Ridiculously Open Online Self Training Sites
email: marc [at] [no-spam.]roosts.org
description: > # this means to ignore newlines until "baseurl:"
  I have no idea what description to put yet that says anything more
  than what the title already says. I guess I have to come back to this
  later.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.roosts.org" # the base hostname & protocol for your site
github_username:  vegantriathlete

# Build settings
markdown: kramdown

kramdown:
  input: GFM
