# Site settings
name: R.O.O.S.T.S.
title: Ridiculously Open Online Self Training Sites
email: marc [at] no-spam.roosts.org
description: > # this means to ignore newlines until "baseurl:"
  This is the portal for all things R.O.O.S.T.S. It is proudly hosted on GitHub.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.roosts.org" # the base hostname & protocol for your site
github_username:  roosts

# Build settings
markdown: kramdown

kramdown:
  input: GFM

collections:
  primary:
    output: true
  secondary:
    output : true
